-- =========================================================================
-- SYSTEM CONFIGURATION & EXTENSIONS
-- =========================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. TABEL PROFILES (Manajemen Akses & Autentikasi)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email text NOT NULL,
    full_name text,
    role text DEFAULT 'user'::text,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_email_key UNIQUE (email)
);

-- =========================================================================
-- 2. TABEL JOBS (Manajemen Lowongan Kerja)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.jobs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text NOT NULL,
    company_name text NOT NULL,
    location text,
    description text,
    apply_url text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

-- =========================================================================
-- 3. TABEL EVENTS (Manajemen Workshops & Seminar)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.events (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text NOT NULL,
    description text,
    location text,
    register_url text,
    date timestamp without time zone,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

-- =========================================================================
-- 4. TABEL POSTS (Manajemen Blog / Edukasi Karier)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.posts (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text NOT NULL,
    slug text NOT NULL,
    content text,
    cover_image text,
    published boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT posts_pkey PRIMARY KEY (id),
    CONSTRAINT posts_slug_key UNIQUE (slug)
);

-- =========================================================================
-- 5. TABEL ROADMAPS (Manajemen Panduan Karier)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.roadmaps (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    category text,
    title text NOT NULL,
    intro text,
    level_1_title text,
    level_1_desc text,
    level_2_title text,
    level_2_desc text,
    level_3_title text,
    level_3_desc text,
    tools text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT roadmaps_pkey PRIMARY KEY (id)
);

-- =========================================================================
-- 6. TABEL SURVEYS & RESPONSES (Arsitektur Kuesioner Utama)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.surveys (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text NOT NULL,
    description text,
    schema jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT surveys_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.responses (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    survey_id uuid NOT NULL,
    user_id uuid,
    user_email text,
    answers jsonb,
    submitted_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT responses_pkey PRIMARY KEY (id)
);

-- =========================================================================
-- 7. GRUP TABEL KUESIONER INTERNAL (Soal, Opsi, & Hasil)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.kuesioner_soal (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kode_soal text NOT NULL,
    pertanyaan text NOT NULL,
    tipe_input text,
    opsi_jawaban text,
    syarat_kode text,
    syarat_nilai text,
    link_file text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT kuesioner_soal_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kuesioner_opsi (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    kode_soal text NOT NULL,
    kode_opsi text NOT NULL,
    teks_opsi text,
    CONSTRAINT kuesioner_opsi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kuesioner_hasil (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email_mahasiswa text NOT NULL,
    jawaban jsonb,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT kuesioner_hasil_pkey PRIMARY KEY (id)
);

-- =========================================================================
-- ROW LEVEL SECURITY (RLS) CONFIGURATIONS
-- =========================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;

-- Policy dasar biar sistem lancar di server lokal/baru
CREATE POLICY "Allow public read access" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.surveys FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.responses FOR SELECT USING (true);